### ISSUE TITLE
id_rsa is a private key...

### ISSUE THREAD

**Issue by sk8forether** [jeroenpeeters/docker-ssh#42] opened 2018-05-25 19:12 UTC
Perhaps you didn't mean to include this?

**Comment by bbarker** [comment] 2018-05-25 19:18
better yet there's a public key included

**Comment by jrddunbr** [comment] 2018-05-25 19:30
Drat! This is what happens when you hesitate on making an issue; I made a duplicate :/ https://github.com/jeroenpeeters/docker-ssh/issues/43

**Comment by jeroenpeeters** [comment] 2018-06-08 12:52
Duplicate of #43

**Closed as completed by jeroenpeeters** 2018-06-08 12:52 UTC
